# Generated by Django 4.0.5 on 2023-04-20 01:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_product_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='emmail',
            new_name='email',
        ),
    ]
